### ISSUE TITLE
But in example mnist_clifford_qnn.py 

### ISSUE THREAD

**Issue by yezhuoyang** [mit-han-lab/torchquantum#245] opened 2024-02-25 18:53 UTC
When I tried to run the example:

\torchquantum\examples\clifford_qnn\mnist_clifford_qnn.py

There is an error:

![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/552d5e54-819f-405e-b46c-71ba3033d291)

**Comment by yezhuoyang** [comment] 2024-02-25 18:54
It seems to be a bug in the encoding function:

![image](https://github.com/mit-han-lab/torchquantum/assets/34168020/63efeb55-5012-4cb8-9f76-2ea1aafa18b2)

**Comment by GenericP3rson** [comment] 2024-03-10 02:45
I’m going to close this since it’s a duplicate of #213. It’s on our radar to get fixed!

**Closed by GenericP3rson** 2024-03-10 02:45 UTC
